DOMAIN = "wmc"

CONF_SENSOR_INDOOR_TEMP = "sensor_indoor_temp"
CONF_SENSOR_INDOOR_HUMIDITY = "sensor_indoor_humidity"
CONF_SENSOR_OUTDOOR_TEMP = "sensor_outdoor_temp"
CONF_SENSOR_OUTDOOR_HUMIDITY = "sensor_outdoor_humidity"
CONF_LOW_SPEED = "low_speed"
CONF_HIGH_SPEED = "high_speed"
CONF_DELTA_TRIGGER = "delta_trigger"
CONF_TARGET_OFFSET = "target_offset"
CONF_MIN_ON_TIME = "min_on_time"
CONF_MAX_ON_TIME = "max_on_time"
CONF_SAMPLE_INTERVAL = "sample_interval"
CONF_MIN_HUMIDITY = "min_humidity"
CONF_UNIQUE_ID = "unique_id"
